apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: busybox-go-dc-operator
spec:
  replicas: 1
  selector:
      name: busybox-go-dc-operator
  template:
    metadata:
      labels:
        name: busybox-go-dc-operator
    spec:
      serviceAccountName: busybox-go-dc-operator
      containers:
        - name: busybox-go-dc-operator
          # Replace this with the built image name
          image: quay.io/kajolasabe/busybox-go-dc-operator:v0.0.1
          command:
          - busybox-go-dc-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "busybox-go-operator"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "helloworld"
        from:
          kind: "ImageStreamTag"
          name: "busybox-go-dc-operator:latest"
  strategy:
    type: "Rolling"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
